version: '3'

tasks:
  mandatory-task:
    cmds:
      - PYTHONPATH=.. python src/mandatory_task/convert.py
    silent: true

  optional-task-1:
    cmds:
      - PYTHONPATH=.. python src/optional_task_1/convert.py
    silent: true

  optional-task-2:
    cmds:
      - PYTHONPATH=.. python src/optional_task_2/convert.py
    silent: true

  optional-task-3:
    cmds:
      - PYTHONPATH=.. python src/optional_task_3/convert.py
    silent: true

  optional-task-4:
    cmds:
      - PYTHONPATH=.. python src/optional_task_4/benchmark.py
    silent: true

  all:
    cmds:
      - task: mandatory-task
      - task: optional-task-1
      - task: optional-task-2
      - task: optional-task-3
      - task: optional-task-4

  clean:
    cmds:
      - rm -f src/*/data/*.bin src/*/data/*.toml src/*/data/*.xml
    ignore_error: true
    silent: true
