name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push changes to GitLab
        env:
          IFMO_GITLAB_TOKEN: ${{ secrets.IFMO_GITLAB_TOKEN }}
        run: |
          git config --global user.name "GitHub CI"
          git config --global user.email "actions@github.com"
          
          git remote add gitlab https://oauth2:${IFMO_GITLAB_TOKEN}@gitlab.se.ifmo.ru/mikhalexandr/informatics.git

          git fetch gitlab master || true
          git push --force gitlab HEAD:master
